[programs.devnet]
save_for_later = "36KXz84PkdRfNQQXzNpswX3s5d5fCPmmqFKhNd31Yd8p"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/cone/.config/solana/id.json"

[scripts]
test = "npx ts-node tests/save-for-later.ts"
